# Make me postgresql image

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: piscine_django
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    
volumes:
  db_data:
    driver: local